services:
  # Spring Boot Backend Service
  - type: web
    name: attenx-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/attenx-backend-1.0.0.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8080
      - key: MYSQLHOST
        value: switchback.proxy.rlwy.net
      - key: MYSQLPORT
        value: 45149
      - key: MYSQLDATABASE
        value: railway
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: bAFzLPYQccDyqaAhAGUlkmSUUKPTJgLz
      - key: SPRING_PROFILES_ACTIVE
        value: prod
