services:
  # Spring Boot Backend Service
  - type: web
    name: attenx-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: MYSQLHOST
        value: switchback.proxy.rlwy.net
      - key: MYSQLPORT
        value: 45149
      - key: MYSQLDATABASE
        value: railway
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: bAFzLPYQccDyqaAhAGUlkmSUUKPTJgLz
      - key: SPRING_PROFILES_ACTIVE
        value: prod
